user = User.create(first_name: 'Serj', email: 'admin@gmail.com', password: 'Test1234!')
rest1 = Restaurant.create(name: 'Loggerhead', address: 'Washington str.1', phone: '23232323')
rest2 = Restaurant.create(name: 'Savoy', address: 'London str.', phone: '3232323')
menu1 = Menu.create(name: 'Summer menu', restaurant_id: rest1.id)
menu2 = Menu.create(name: 'Winter menu', restaurant_id: rest2.id)
dish1 = Dish.create(name: 'Stake', description: 'Well done', price: 100, weight: 0.500)
dish2 = Dish.create(name: 'Pasta Nero', description: 'Italian pasta', price: 150, weight: 0.300)
order = Order.create(user_id: user.id, restaurant_id: rest1.id)
